config/routes.rb
Sarperlipopette::Application.routes.draw do
  resources :nagus, only: [:new, :create, :show]
  resources :satellites
  get "date_and_time/new"
  post "date_and_time/create"
  get "date_and_time/show"
  get "nanu/new"
  get "nanu/create"
  get "nanu/show"
  root :to => "home#index"
end

app/models/counter.rb
class Counter < ActiveRecord::Base
end

app/models/galileo_satellite.rb
class GalileoSatellite < Satellite

end

app/models/glonass_satellite.rb
class GlonassSatellite < Satellite

  validates :glonass_plane_slot, format: { with: %r{\A(?:|\d\d/\d\d)\z},
                                        message: "expected format ##/##" }

end

app/models/gps_satellite.rb
class GpsSatellite < Satellite

end

app/models/nagu.rb
class Nagu
  # include ActiveModel::Validations
  # include ActiveModel::Conversion
  include ActiveModel::Model

  attr_accessor :sat_id, :unavailability_start_date, :unavailability_end_date

  # validates_presence_of :sat_id, :unavailability_start_date, :unavailability_start_date
end

app/models/satellite.rb
class Satellite < ActiveRecord::Base
  def constellation
    type.sub(/Satellite/, "")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # before_action :set_locale
   
  def set_locale
      logger.debug "* Accept-Language: #{request.env['HTTP_ACCEPT_LANGUAGE']}"
        I18n.locale = extract_locale_from_accept_language_header
          logger.debug "* Locale set to '#{I18n.locale}'"
  end
  private
  def extract_locale_from_accept_language_header
      request.env['HTTP_ACCEPT_LANGUAGE'].scan(/^[a-z]{2}/).first
  end
end

app/controllers/date_and_time_controller.rb
class DateAndTimeController < ApplicationController
  def new
  end

  def create
    @posix_date = params[:posix_date]
    @human_date = Time.at(@posix_date.to_f).utc
    render 'show'
  end

  def show
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/nagus_controller.rb
class NagusController < ApplicationController
  def new
    @nagu = Nagu.new
  end

  def create
    params[:nagu][:unavailability_start_date] = to_date :unavailability_start_date
    params[:nagu][:unavailability_end_date] = to_date :unavailability_end_date

    # Hack needed as ActiveModel does not currently support multiparameters
    params[:nagu].reject!{ |p| p.match /\)/ }

    satellite = GlonassSatellite.where(cospas_sarsat_id: params[:nagu][:sat_id]).first

    nagu = Nagu.new(nagu_params)
    begin
      @nagu = NaguPresenter.new(nagu, satellite)
      response.headers['Content-Disposition'] = 'attachment; filename=nagu.txt'
      render :show, content_type: 'text/plain', layout: false
    rescue InvalidNaguSatellite => e
      @nagu = nagu
      flash.now[:alert ] = "The Sat ID you provided is not suitable for the generation of a NAGU"
      render :new
    end
  end

  def show
  end

  private 

  def nagu_params
    params.require(:nagu).permit(:sat_id, :unavailability_start_date, :unavailability_end_date)
  end

  def to_date(field)
    Time.utc(params[:nagu]["#{field}(1i)"].to_i,
             params[:nagu]["#{field}(2i)"].to_i,
             params[:nagu]["#{field}(3i)"].to_i,
             params[:nagu]["#{field}(4i)"].to_i,
             params[:nagu]["#{field}(5i)"].to_i,
            )
  end
end

app/controllers/nanu_controller.rb
class NanuController < ApplicationController
  def new
  end

  def create
  end

  def show
  end
end

app/controllers/satellites_controller.rb
class SatellitesController < ApplicationController

  def index
    @satellites = Satellite.all(order: :name)
  end

  def show
    @satellite = Satellite.find(params[:id])
  end

  def edit
    @satellite = Satellite.find(params[:id])
  end

  def update
    @satellite = Satellite.find(params[:id])

    if @satellite.update(satellite_params)
      redirect_to satellite_url
    else
      flash.now[:alert] = "Update failed, check your inputs"
      render 'edit'
    end
  end

  private 
  
  def satellite_params
    params.require(:satellite).permit(:name, :cospas_sarsat_id, :norad_id, :glonass_id, :glonass_plane_slot, :cosmos_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/date_and_time_helper.rb
module DateAndTimeHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/nagus_helper.rb
module NagusHelper
  def nagu_next_sequence_number
    nagu_counter = Counter.find(:first, conditions: ["name = ?", "nagu"])
    nagu_counter.increment!(:value)
    nagu_counter.value
  end
end

app/helpers/nanu_helper.rb
module NanuHelper
end

app/helpers/satellite_helper.rb
module SatelliteHelper

  def cosmos_id_from_cospas_sarsat_id(id)
    try {GlonassSatellite.where(cospas_sarsat_id: id).cosmos_id}
  end

end

app/helpers/satellites_helper.rb
module SatellitesHelper
end

app/views/common/_form_input.html.haml
- type ||= :text
.form-group
  %label.col-sm-2.control-label{for: attribute.to_s} #{label} 
  .col-sm-4
    - case type
      - when :number
        = f.number_field :norad_id, class: 'form-control'
      - when :text
        = f.text_field attribute, class: 'form-control'

app/views/common/_tablesorter_filter_option_help.html.haml
%p
  .text-right
    %small
      %a{"href" => "#", "data-toggle" => "modal", "data-target" => "#filterOptionModal"}
        .glyphicon.glyphicon-question-sign
        filter options

.modal.fade#filterOptionModal{"tabindex" => "-1", "role" => "dialog", "aria-labelledby" => "filterOptionModalLabel",  "aria-hidden" => "true"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"type" => "button", "data-dismiss" => "modal", "aria-hidden" => "true"} &times
        %h4.modal-title#filterOptionModalLabel Filter options
      .modal-body 
        %table.table
          %thead
            %tr
              %th Type
              %th Description
              %th Examples
          %tbody
            %tr
              %td text
              %td Any text entered in the filter will match text found within the column
              %td 
                %button abc
                (finds "abc", "abcd", "abcde", etc); 
                %button Aaron
                (finds "Aaron" and "Philip Aaron Wong")
            %tr
              %td ~
              %td Perform a fuzzy search (matches sequential characters) by adding a tilde to the beginning of the query
              %td
                %button ~bee
                (matches "Bruce Lee" and "Brenda Dexter") or 
                %button ~piano
                (matches "Philip Aaron Wongg")
            %tr
              %td "
              %td To exactly match the search query, add a quote, apostrophe or equal sign to the beginning and/or end of the query
              %td
                %button abc"
                or 
                %button abc= 
                (exactly match "abc")
            %tr
              %td ?
              %td Wildcard for a single, non-space character
              %td
                %button J?n 
                (finds "Jan" and "Jun", but not "Joan")
            %tr
              %td *
              %td Wildcard for zero or more non-nonspace characters
              %td 
                %button B*k 
                (matches "Black" and "Book")
            %tr
              %td /\d/
              %td Add any regex to the query to use in the query
              %td 
                %button /b[aeiou]g/i 
                (finds "bag", "beg", "BIG", "Bug", etc)
            %tr
              %td &lt; &lt;= &gt;= &gt;
              %td Find alphabetical or numerical values less than or greater than or equal to the filtered query
              %td 
                %button &gt;=10
                (find  values greater than or equal to 10)
            %tr
              %td !
              %td Not operator. Filter the column with content that do not match the query.
              %td
                %button !fe 
                (hide rows with "female" in that column, but shows rows with "male")
            %tr
              %td &amp;&amp;  or  AND 
              %td Logical "and". Filter the column for content that matchhes text from either side of the operator.
              %td
                %button box && bat 
                (matches a column cell that contains both "box" and "bat")
            %tr
              %td | or  OR 
              %td Logical "or" (Vertical bar). Filter the column for containt that matches text from either side of the bar
              %td
                %button box|bat
                (matches a column cell with either "box" or "bat")
            %tr
              %td - or to
              %td Find a range of values. Make sure there is a space before and after the dash (or the word "to")
              %td
                %button 10 - 30
                or 
                %button 10 to 30
                (matches values between 10 and 30)

app/views/date_and_time/_posix_to_human_form.html.haml
%h2 POSIX date to human date conversion
%hr
= form_tag({controller: "date_and_time", action: "create"}, class: "form-horizontal", role: "form",  method: "post") do
  .well
    %fielset
      %legend Enter POSIX date
      .form-group
        = label_tag(:posix_date, "POSIX Date", class: "col-lg-2 control-label")
        .col-lg-4
          = text_field_tag(:posix_date, nil, class: "form-control", type: "number", placeholder: "POSIX date in seconds, ex: '#{Time.now.to_f}' ")
  = submit_tag("Convert", class: "btn btn-primary")

app/views/date_and_time/create.html.haml
%h2 DateAndTime#create
%p Find me in app/views/date_and_time/create.html.haml

app/views/date_and_time/new.html.haml
= render "posix_to_human_form"

app/views/date_and_time/show.html.haml
= render "posix_to_human_form"
%p
  %table.table
    %thead
      %th POSIX Date
      %th Human Date
    %tbody
      %tr
        %td #{@posix_date}
        %td #{@human_date}

app/views/home/index.html.haml
.jumbotron
  .animated.fadeInRightBig
    %h1.sar-enhanced perlipopette
    %p Your toolbox for SARGS tests.

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "danger"}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
.navbar.navbar-default.navbar-fixed-top{"role" => "banner"}
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", "type" => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to root_path, class: 'navbar-brand animated flash' do
        %strong
          %em.brand.sar-enhanced perlipopette
    %nav.collapse.navbar-collapse{"role" => "navigation"}
      %ul.nav.navbar-nav
        -# %li.dropdown{class: controller.controller_name == "nanu" && 'active'}
        -#   %a.dropdown-toggle{"data-toggle" => "dropdown", "href" => "#"}
        -#     %span.glyphicon.glyphicon-list-alt
        -#     NANU
        -#     %span.caret
        -#   %ul.dropdown-menu
        -#     %li
        -#       = link_to "Create", nanu_new_path
        %li.dropdown{class: controller.controller_name == "nagus" && 'active'}
          %a.dropdown-toggle{"data-toggle" => "dropdown", "href" => "#"}
            %span.glyphicon.glyphicon-list-alt
            NAGU
            %span.caret
          %ul.dropdown-menu
            %li
              = link_to "Create", new_nagu_path
        %li.dropdown{class: controller.controller_name == "date_and_time" && 'active'}
          %a.dropdown-toggle{"data-toggle" => "dropdown", "href" => "#"}
            %span.glyphicon.glyphicon-time
            Date and time
            %span.caret
          %ul.dropdown-menu
            %li
              = link_to "POSIX to human", date_and_time_new_path
        %li.dropdown{class: controller.controller_name == "satellites" && 'active'}
          %a.dropdown-toggle{"data-toggle" => "dropdown", "href" => "#"}
            %span.glyphicon.glyphicon-transfer
            Satellites
            %span.caret
          %ul.dropdown-menu
            %li
              = link_to "Show registered", satellites_path

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Sarperlipopette'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Sarperlipopette'}"}
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    .bs-top-callout
      .container
        = render 'layouts/messages'
        = yield

app/views/nagus/create.html.haml
%h2 Nagus#create
%p Find me in app/views/nagus/create.html.haml

app/views/nagus/new.html.haml
%h2 NAGU Creation
%hr

  = form_for @nagu, url: {action: 'create'}, html: {class: 'form-horizontal', role: 'form'} do |f|
    .well
      %fieldset 
        %legend Enter NAGU input parameters
      .form-group
        %label.col-lg-2.control-label{for: 'nagu_sat_id'} Sat ID
        .col-lg-4
          = f.number_field :sat_id, class: 'form-control'
          %span.help-block Enter a Cospas/Sarsat satellite Id. 
      .form-group
        %label.col-lg-2.control-label{for: 'nagu_unavailability_start_date'} Unavailability start date
        .col-lg-4
          = datetime_select :nagu, :unavailability_start_date, class: 'form-control', start_year: Date.today.year
      .form-group
        %label.col-lg-2.control-label{for: 'nagu_unavailability_end_date'} Unavailability end date
        .col-lg-4
          = datetime_select :nagu, :unavailability_end_date, class: 'form-control', start_year: Date.today.year, default: 2.days.from_now
    = f.submit 'Create', class: 'btn btn-primary'

app/views/nagus/show.html.erb
                   1.STATUS Information Group
 
                  GLONASS Constellation Status
                      ( <%= @nagu.status_date %>)
 
|GLONASS|Cosmos|Plane/|Frequ.|   Launch   |   Intro    |  Status   |  Outage    |
|number |number| slot |chann.|    date    |    date    |           |    date    |
|-------|------|------|------|------------|------------|-----------|------------|
|  730  | 2456 | 1/01 |  01  | 14.12.2009 | 30.01.2010 | operating | .......... |
|  747  | 2485 | 1/02 |  -4  | 26.04.2013 | 04.07.2013 | operating | .......... |
|  744  | 2476 | 1/03 |  05  | 04.11.2011 | 08.12.2011 | operating | .......... |
|  742  | 2474 | 1/04 |  06  | 02.10.2011 | 25.10.2011 | operating | .......... |
|  734  | 2458 | 1/05 |  01  | 14.12.2009 | 10.01.2010 | operating | .......... |
|  733  | 2457 | 1/06 |  -4  | 14.12.2009 | 24.01.2010 | operating | .......... |
|  745  | 2477 | 1/07 |  05  | 04.11.2011 | 18.12.2011 | operating | .......... |
|  743  | 2475 | 1/08 |  06  | 14.11.2011 | 25.12.2011 | operating | .......... |
|  736  | 2464 | 2/09 |  -2  | 02.09.2010 | 04.10.2010 | operating | .......... |
|  717  | 2426 | 2/10 |  -7  | 25.12.2006 | 03.04.2007 | operating | .......... |
|  723  | 2436 | 2/11 |  00  | 25.12.2007 | 22.01.2008 | operating | .......... |
|  737  | 2465 | 2/12 |  -1  | 02.09.2010 | 11.10.2010 | operating | .......... |
|  721  | 2434 | 2/13 |  -2  | 25.12.2007 | 08.02.2008 | operating | .......... |
|  715  | 2424 | 2/14 |  -7  | 25.12.2006 | 03.04.2007 | operating | .......... |
|  716  | 2425 | 2/15 |  00  | 25.12.2006 | 12.10.2007 | operating | .......... |
|  738  | 2466 | 2/16 |  -1  | 02.09.2010 | 12.10.2010 | operating | .......... |
|  746  | 2478 | 3/17 |  04  | 28.11.2011 | 23.12.2011 | operating | .......... |
|  724  | 2442 | 3/18 |  -3  | 25.09.2008 | 26.10.2008 | operating | .......... |
|  720  | 2433 | 3/19 |  03  | 26.10.2007 | 25.11.2007 | operating | .......... |
|  719  | 2432 | 3/20 |  02  | 26.10.2007 | 27.11.2007 | operating | .......... |
|  725  | 2443 | 3/21 |  04  | 25.09.2008 | 05.11.2008 | operating | .......... |
|  731  | 2459 | 3/22 |  -3  | 02.03.2010 | 28.03.2010 | operating | .......... |
|  732  | 2460 | 3/23 |  03  | 02.03.2010 | 28.03.2010 | operating | .......... |
|  735  | 2461 | 3/24 |  02  | 02.03.2010 | 28.03.2010 | operating | .......... |
 
Note: All the dates (DD.MM.YY) are given at Moscow Time (UTC+0300)
 
 
                2.SUMMARY Information Group

SUBJ:GLONASS STATUS  <%= @nagu.summary_date %>
 
1.SATELLITES, PLANES, SLOTS AND CHANNELS
 
| Plane 1/ slot | 01 | 02 | 03 | 04 | 05 | 06 | 07 | 08 |
|       Channel | 01 | -4 | 05 | 06 | 01 | -4 | 05 | 06 |  
|---------------|----|----|----|----|----|----|----|----|
| Plane 2/ slot | 09 | 10 | 11 | 12 | 13 | 14 | 15 | 16 |
|       Channel | -2 | -7 | 00 | -1 | -2 | -7 | 00 | -1 |  
|---------------|----|----|----|----|----|----|----|----|
| Plane 3/ slot | 17 | 18 | 19 | 20 | 21 | 22 | 23 | 24 |
|       Channel | 04 | -3 | 03 | 02 | 04 | -3 | 03 | 02 |  
 
2.CURRENT ADVISORIES (ADV) AND FORECASTS (FCST)
INFORMATION IS REPEATED FOR ONE MONTH AFTER EVENT CONCLUDES.
ALL THE DATES (DD.MM.YY) ARE GIVEN AT MOSCOW TIME (UTC+0300)
 
 
A. FORECASTS
NAGU-MSG.DATE-TIME-SL/CH-TYPE-SUMMARY

 

B. ADVISORIES

NAGU-MSG.DATE-TIME-SL/CH-TYPE-SUMMARY

 <%=@nagu.slot_id%>-<%=@nagu.emission_time%>-<%=@nagu.plane_slot%>-ADVS-UNUSABLE <%=@nagu.slot_period%>
 
C. GENERAL: NO IMPACT, INFORMATIONAL PURPOSE ONLY
NAGU-MSG.DATE-TIME-SL/CH-TYPE-SUMMAR

 
                     3.NAGU Information Group

 
<%=@nagu.slot_id%>
NOTICE ADVISORY TO GLONASS USERS (NAGU) <%=@nagu.slot_id%>
SUBJ: <%=@nagu.plane_slot%> (<%=@nagu.glonass_id%>) UNUSABLE <%=@nagu.start_date_s%>-<%=@nagu.end_date_s%> MT
1.CONDITION: <%=@nagu.plane_slot%> (<%=@nagu.glonass_id%>) WAS UNUSABLE
 SINCE <%=@nagu.start_date_s%> UNTIL <%=@nagu.end_date_s%>
 MT (UTC+0300) DUE TO MAINTENANCE
2.USERS ARE REMINDED TO UPDATE ALMANACS IF NECESSARY

app/views/nanu/create.html.haml
%h1 Nanu#create
%p Find me in app/views/nanu/create.html.haml

app/views/nanu/new.html.haml
%h1 Create a NANU

app/views/nanu/show.html.haml
%h1 Nanu#show
%p Find me in app/views/nanu/show.html.haml

app/views/satellites/_edit_glonass.html.haml
= f.input :glonass_id
= f.input :cosmos_id
= f.input :glonass_plane_slot

app/views/satellites/_show_glonass.html.haml
%p
  %dt Glonass Id.
  %dd #{@satellite.glonass_id || "Undefined"}
%p
  %dt COSMOS Id.
  %dd #{@satellite.cosmos_id}
%p
  %dt Plane/Slot
  %dd #{@satellite.glonass_plane_slot}

app/views/satellites/edit.html.haml
%h2 Satellite #{@satellite.name}
%hr
  = simple_form_for @satellite, as: :satellite, url: {controller: "satellites", action: 'update'}, role: "form"  do |f|
    .well
      %fieldset
        %legend Edit satellite
        = f.input :name
        = f.input :cospas_sarsat_id
        = f.input :norad_id
        = render partial: 'edit_glonass', locals: {f: f}
    = f.button :submit

app/views/satellites/index.html.haml
%h2 Registered Satellites
%hr

= render 'common/tablesorter_filter_option_help'
%table.table.table-condensed.table-hover.sortable
  %thead
    %tr
      %th Name
      %th.filter-select.filter-exact{"data-placeholder" => "Choose ..."} Constellation
      %th Cospas Sarsat Id
      %th Norad Id
      %th Operations
  %tfoot
    %tr
      %th.ts-pager.form-horizontal{"colspan" => "5"}
        %button.btn.first
          %i.glyphicon.glyphicon-step-backward
        %button.btn.prev
          %i.glyphicon.glyphicon-backward
        %span.pagedisplay
        %button.btn.next
          %i.glyphicon.glyphicon-forward
        %button.btn.last
          %i.glyphicon.glyphicon-step-forward
        %select.pagesize.input-mini{"title" => "Select page size"}
          %option{"selectected" => "selected", "value"=> "10"} 10
          %option{"value" => "20"} 20
          %option{"value" => "30"} 30
          %option{"value" => "40"} 40
        %select.pagenum.input-mini{"title" => "Select page number"}
  %tbody
    - @satellites.each do |sat|
      %tr
        %td #{ sat.name }
        %td #{ sat.constellation }
        %td #{ sat.cospas_sarsat_id }
        %td #{ sat.norad_id }
        %td 
          %a{"href" => satellite_path(sat)}
            %i.glyphicon.glyphicon-info-sign
          %a{"href" => edit_satellite_path(sat)}
            %i.glyphicon.glyphicon-edit
          %a{"href" => "http://www.satflare.com/track.asp?q=#{sat.norad_id}#TOP", "target" => "_blank"}
            %i.glyphicon.glyphicon-globe

app/views/satellites/show.html.haml
%h2 Satellite #{@satellite.name}
%hr
.well
  %legend Satellite information
  %dl.dl.dl-horizontal
    %p
      %dt Name
      %dd #{@satellite.name}
    %p
      %dt Type
      %dd #{@satellite.class.name}
    %p
      %dt Cospas Sarsat Id.
      %dd #{@satellite.cospas_sarsat_id || "Undefined"}
    %p
      %dt NORAD Id.
      %dd #{@satellite.norad_id}
    = render "show_#{@satellite.constellation.downcase}"
%a.btn.btn-primary{"href" => edit_satellite_path(@satellite)} Edit